frontend_news:
    resource: "@FrontendNewsBundle/Controller/"
    type:     annotation

backend_user:
    resource: "@UserBundle/Controller/"
    type:     annotation

app:
    resource: "@HomeBundle/Controller/"
    type:     annotation
